apiVersion: skaffold/v2beta25
kind: Config
deploy: 
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: your-dockerhub-username/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: 'src/**/*.ts'
            dest : .
    - image: your-dockerhub-username/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image : your-dockerhub-username/client
      context: client
      docker: 
        dockerfile : Dockerfile
      sync: 
        manual:
          - src: '**/*.jsx'
            dest: .
          - src: '**/*.js'
            dest: .
    - image : your-dockerhub-username/tickets
      context : tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.ts'
            dest : .
    - image : your-dockerhub-username/expiration
      context : expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.ts'
            dest : .
    - image : your-dockerhub-username/payments
      context : payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.ts'
            dest : .